CREATE TABLE characters (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  level INTEGER NOT NULL,
  class TEXT NOT NULL,
  is_expansion BOOLEAN NOT NULL,
  has_died BOOLEAN NOT NULL,
  is_hardcore BOOLEAN NOT NULL,
  is_ladder BOOLEAN NOT NULL,
  saved_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
